// Experimental only: all thresholds/ranges remain physical-device unverified.
export const REAR_STAND=Object.freeze({
  DEFAULT_ENABLED:false,
  UNOBSERVABLE_SEPARATION_SIN:.01, MAX_CONDITION_NUMBER:20,
  STEERING_LIMIT_DEG:100, BODY_YAW_LIMIT_DEG:15,
  RESIDUAL_CHECK_DEG:.5, RESIDUAL_INVALID_DEG:2,
  MAX_ITERATIONS:24, MAX_STEP_DEG:12, DIFFERENCE_STEP_DEG:.001,
  CONVERGENCE_STEP_DEG:1e-7, BOUND_MARGIN_DEG:.001,
});
